@Api_HostAddress = https://localhost:44379
@TenantId = 11111111-1111-1111-1111-111111111111

### Health 
GET {{Api_HostAddress}}/api/health
Accept: application/json

### Tenant 
GET {{Api_HostAddress}}/api/tenant
Accept: application/json
X-Tenant-Id: {{TenantId}}